name: Silksong Subreddit Archiver

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC (05:30 IST)
  workflow_dispatch: {}    # allows manual trigger from the Actions tab

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run scraper
        run: python reddit_scraper.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reddit_archive.md
          if git diff --cached --quiet; then
            echo "No new posts to commit"
          else
            git commit -m "Update r/Silksong posts for $(date -u +'%Y-%m-%d') [skip ci]"
            git push
          fi

